version: '3.7'

services:
  datafy_backend:
    container_name: datafy_backend
    restart: always
    build: .
    image: davidbuzatumarian/datafy_ts_project
    environment:
      - PORT=5000
      - NODE_ENV=production
    ports:
      - '5000:5000'
